import React, { useState, useEffect, useCallback } from 'react'
import { Search, BookOpen, Clock, ChevronRight, Loader2, X } from 'lucide-react'
import { getArticles } from '../services/firestore'
import { Card, CardContent } from '../components/ui/Card'
import Badge from '../components/ui/Badge'
import Button from '../components/ui/Button'
import { useDebouncedValue } from '../hooks/useDebounce'
import { formatDate, getCategoryIcon } from '../utils/formatters'
import { clsx } from 'clsx'

const CATEGORIES = [
  { id: null, label: 'All' },
  { id: 'climate_change', label: '🌡️ Climate Change' },
  { id: 'renewable_energy', label: '☀️ Renewable Energy' },
  { id: 'waste_management', label: '🗑️ Waste Management' },
  { id: 'sustainable_lifestyle', label: '🌱 Sustainable Living' },
  { id: 'carbon_neutrality', label: '🌍 Carbon Neutrality' },
]

const SAMPLE_ARTICLES = [
  {
    id: '1',
    title: 'Understanding Your Carbon Footprint',
    category: 'climate_change',
    summary: 'Learn what a carbon footprint is, how it\'s measured, and why reducing it matters for our planet\'s future.',
    readTime: '5 min',
    publishedAt: { toDate: () => new Date('2025-01-15') },
    content: `
      <h3>What is a Carbon Footprint?</h3>
      <p>A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average is closer to 4 tons.</p>
      <br/>
      <h3>Why Does It Matter?</h3>
      <p>When greenhouse gases enter the atmosphere, they trap heat from the sun, leading to a gradual warming of the earth (global warming). This disrupts weather patterns, melts polar ice caps, and threatens biodiversity.</p>
      <br/>
      <h3>How is it Measured?</h3>
      <p>Carbon footprints are generally measured in equivalent tons of CO2. It takes into account:</p>
      <ul style="list-style-type: disc; margin-left: 20px;">
        <li><strong>Transportation:</strong> Driving, flying, and public transit.</li>
        <li><strong>Energy:</strong> Household electricity and heating.</li>
        <li><strong>Food:</strong> Meat consumption, food miles, and waste.</li>
        <li><strong>Purchases:</strong> The lifecycle footprint of clothing, electronics, and goods.</li>
      </ul>
    `
  },
  {
    id: '2',
    title: 'Top 10 Ways to Reduce Home Energy Use',
    category: 'renewable_energy',
    summary: 'Simple, practical steps to cut your electricity bill and lower your home\'s carbon emissions by up to 30%.',
    readTime: '7 min',
    publishedAt: { toDate: () => new Date('2025-02-01') },
    content: `
      <h3>Simple Tweaks with Big Impact</h3>
      <p>Reducing your home energy use doesn't have to mean major renovations. Here are some of the most effective things you can do today:</p>
      <ol style="list-style-type: decimal; margin-left: 20px;">
        <li><strong>Switch to LED Bulbs:</strong> LED lights use 75% less energy and last 25 times longer than incandescent lighting.</li>
        <li><strong>Unplug Vampire Appliances:</strong> Electronics like TVs and chargers draw power even when turned off. Use smart power strips to cut them off completely.</li>
        <li><strong>Wash Clothes in Cold Water:</strong> Heating water accounts for about 90% of the energy used by a washing machine.</li>
        <li><strong>Adjust Your Thermostat:</strong> Lowering your thermostat by just 2 degrees in winter and raising it in summer can save significant energy.</li>
        <li><strong>Seal Leaks:</strong> Weather-strip doors and windows to prevent drafts and keep your climate control efficient.</li>
      </ol>
      <br/>
      <p>Start small. Even implementing just one or two of these changes can noticeably reduce your monthly energy bill and lower your carbon emissions.</p>
    `
  },
  {
    id: '3',
    title: 'The Zero-Waste Kitchen',
    category: 'waste_management',
    summary: 'Transform your kitchen habits with composting, meal planning, and smart shopping to eliminate food waste.',
    readTime: '6 min',
    publishedAt: { toDate: () => new Date('2025-02-20') },
    content: `
      <h3>Rethinking Food Waste</h3>
      <p>Roughly one-third of the food produced in the world for human consumption every year gets lost or wasted. When food rots in a landfill, it produces methane—a greenhouse gas 25 times more potent than carbon dioxide.</p>
      <br/>
      <h3>Steps to a Zero-Waste Kitchen</h3>
      <ul style="list-style-type: disc; margin-left: 20px;">
        <li><strong>Meal Planning:</strong> Plan your meals for the week before you grocery shop. Buy only what you need.</li>
        <li><strong>Proper Storage:</strong> Learn how to store vegetables correctly so they last longer. Use glass containers instead of plastic wrap.</li>
        <li><strong>Repurpose Scraps:</strong> Save vegetable peels to make homemade broth. Turn stale bread into croutons or breadcrumbs.</li>
        <li><strong>Start Composting:</strong> Even if you live in an apartment, indoor worm bins or countertop composters can handle your organic waste efficiently.</li>
      </ul>
      <br/>
      <p>A zero-waste kitchen is an ongoing journey. Don't aim for perfection immediately; aim to waste a little less each week.</p>
    `
  },
  {
    id: '4',
    title: 'Why Plant-Based Diets Matter for Climate',
    category: 'sustainable_lifestyle',
    summary: 'Discover how shifting toward plant-based foods is one of the most powerful individual climate actions available.',
    readTime: '8 min',
    publishedAt: { toDate: () => new Date('2025-03-05') },
    content: `
      <h3>The Environmental Cost of Meat</h3>
      <p>The global food system is responsible for about one-third of all human-caused greenhouse gas emissions, and the majority of that comes from animal agriculture. Raising livestock requires massive amounts of land, water, and feed.</p>
      <br/>
      <h3>Impact of a Plant-Based Diet</h3>
      <p>Studies show that moving to a plant-based diet can reduce your food-related carbon footprint by up to 73%. But you don't have to go 100% vegan to make a difference.</p>
      <ul style="list-style-type: disc; margin-left: 20px;">
        <li><strong>Meatless Mondays:</strong> Skipping meat just one day a week can save thousands of gallons of water a year.</li>
        <li><strong>Swapping Beef:</strong> Beef is the most carbon-intensive food. Swapping it for chicken or plant-based proteins drastically cuts emissions.</li>
        <li><strong>Focus on Local Produce:</strong> Buying seasonal, locally grown vegetables reduces transportation emissions and supports the local economy.</li>
      </ul>
    `
  },
  {
    id: '5',
    title: 'Carbon Offsetting: Does It Really Work?',
    category: 'carbon_neutrality',
    summary: 'A balanced look at carbon offset programs, their effectiveness, and how to choose verified, high-quality offsets.',
    readTime: '9 min',
    publishedAt: { toDate: () => new Date('2025-03-18') },
    content: `
      <h3>What are Carbon Offsets?</h3>
      <p>Carbon offsetting allows individuals and companies to compensate for their emissions by funding an equivalent carbon dioxide saving elsewhere. This often involves planting trees, funding renewable energy projects, or investing in carbon capture technology.</p>
      <br/>
      <h3>The Pros and Cons</h3>
      <p>While offsetting is better than doing nothing, it is not a silver bullet. Critics argue it gives people a "license to pollute" rather than actually reducing emissions at the source.</p>
      <p>However, when paired with genuine reduction efforts, high-quality offsets are crucial for mitigating unavoidable emissions (like necessary air travel).</p>
      <br/>
      <h3>Choosing Verified Offsets</h3>
      <p>If you choose to buy offsets, ensure they are certified by recognized standards like the Gold Standard or the Verified Carbon Standard (VCS). These organizations verify that the carbon reduction is real, permanent, and would not have happened without the funding.</p>
    `
  },
  {
    id: '6',
    title: 'Solar Panels: A Beginner\'s Guide',
    category: 'renewable_energy',
    summary: 'Everything you need to know about installing solar panels at home — costs, savings, and environmental benefits.',
    readTime: '10 min',
    publishedAt: { toDate: () => new Date('2025-04-02') },
    content: `
      <h3>Why Go Solar?</h3>
      <p>Residential solar panels offer a way to generate clean, renewable energy right on your roof. Not only does this drastically reduce your reliance on fossil-fuel-powered grids, but it also lowers your electricity bills.</p>
      <br/>
      <h3>Understanding the Costs</h3>
      <p>The upfront cost of a solar installation can be significant, but prices have dropped by over 70% in the last decade. Furthermore, many governments offer tax credits and rebates that can cover 20-30% of the total cost.</p>
      <br/>
      <h3>Net Metering</h3>
      <p>If your system generates more electricity than you use during the day, net metering allows you to send that excess energy back to the grid in exchange for credits on your utility bill, essentially spinning your meter backward.</p>
      <p>Before installing, always get quotes from multiple local installers and assess your roof's sunlight exposure.</p>
    `
  },
  {
    id: '7',
    title: 'Sustainable Fashion: Breaking Fast Fashion Habits',
    category: 'sustainable_lifestyle',
    summary: 'How to build a sustainable wardrobe, understand fabric impact, and support ethical fashion brands.',
    readTime: '6 min',
    publishedAt: { toDate: () => new Date('2025-04-15') },
    content: `
      <h3>The Fast Fashion Problem</h3>
      <p>The fashion industry is responsible for 10% of annual global carbon emissions—more than all international flights and maritime shipping combined. "Fast fashion" encourages consumers to buy cheap, trendy garments that fall apart quickly and end up in landfills.</p>
      <br/>
      <h3>How to Shop Sustainably</h3>
      <ul style="list-style-type: disc; margin-left: 20px;">
        <li><strong>Buy Less, Buy Better:</strong> Invest in high-quality, timeless pieces that will last for years.</li>
        <li><strong>Thrift and Second-hand:</strong> Shopping vintage or thrifted clothing entirely bypasses the manufacturing footprint.</li>
        <li><strong>Check the Fabric:</strong> Avoid synthetic materials like polyester (which is essentially plastic and sheds microplastics). Look for organic cotton, linen, hemp, or Tencel.</li>
        <li><strong>Repair Don't Replace:</strong> Learn basic mending skills to fix small holes or missing buttons instead of throwing clothes away.</li>
      </ul>
    `
  },
  {
    id: '8',
    title: 'The Paris Agreement Explained',
    category: 'climate_change',
    summary: 'A plain-English breakdown of the Paris Agreement, its targets, and what it means for countries and individuals.',
    readTime: '8 min',
    publishedAt: { toDate: () => new Date('2025-05-01') },
    content: `
      <h3>What is the Paris Agreement?</h3>
      <p>Adopted in 2015, the Paris Agreement is a legally binding international treaty on climate change. It was adopted by 196 Parties at COP 21 in Paris.</p>
      <br/>
      <h3>The Primary Goals</h3>
      <p>The overarching goal is to limit global warming to well below 2, preferably to 1.5 degrees Celsius, compared to pre-industrial levels. To achieve this long-term temperature goal, countries aim to reach global peaking of greenhouse gas emissions as soon as possible to achieve a climate-neutral world by mid-century.</p>
      <br/>
      <h3>How it Works</h3>
      <p>The Agreement works on a 5-year cycle of increasingly ambitious climate action. Every five years, countries submit updated national climate action plans known as Nationally Determined Contributions (NDCs). It also provides a framework for financial, technical and capacity building support to those countries who need it.</p>
    `
  },
  {
    id: '9',
    title: 'Composting at Home: Getting Started',
    category: 'waste_management',
    summary: 'Step-by-step guide to starting a compost system that can divert up to 30% of household waste from landfill.',
    readTime: '5 min',
    publishedAt: { toDate: () => new Date('2025-05-20') },
    content: `
      <h3>The Magic of Composting</h3>
      <p>Composting accelerates the natural process of decomposition. By creating the right environment for bacteria and fungi, you can turn your food scraps and yard waste into "black gold"—a nutrient-rich fertilizer for your garden.</p>
      <br/>
      <h3>The Basic Recipe: Greens and Browns</h3>
      <p>A successful compost pile requires a balance of nitrogen-rich "Greens" and carbon-rich "Browns".</p>
      <ul style="list-style-type: disc; margin-left: 20px;">
        <li><strong>Greens:</strong> Fruit and vegetable scraps, coffee grounds, grass clippings.</li>
        <li><strong>Browns:</strong> Dry leaves, twigs, shredded newspaper, cardboard.</li>
      </ul>
      <p>Aim for a ratio of about 3 parts Browns to 1 part Greens to keep the pile smelling earthy, not rotten.</p>
      <br/>
      <h3>What NOT to Compost</h3>
      <p>Avoid putting meat, dairy, bones, or oily foods in your home compost, as they can attract pests and create bad odors.</p>
    `
  }
]

export default function EducationHub() {
  const [articles, setArticles] = useState([])
  const [category, setCategory] = useState(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [loading, setLoading] = useState(true)
  const [page, setPage] = useState(1)
  const [activeArticle, setActiveArticle] = useState(null)

  const debouncedSearch = useDebouncedValue(searchQuery, 300)

  useEffect(() => { document.title = 'Education Hub – EcoTrack' }, [])

  useEffect(() => {
    setLoading(true)
    getArticles(category, 20)
      .then(({ articles: data }) => {
        setArticles(data.length > 0 ? data : SAMPLE_ARTICLES)
      })
      .catch(() => setArticles(SAMPLE_ARTICLES))
      .finally(() => setLoading(false))
  }, [category])

  const filtered = articles.filter((a) => {
    if (!debouncedSearch) return true
    const q = debouncedSearch.toLowerCase()
    return a.title?.toLowerCase().includes(q) || a.summary?.toLowerCase().includes(q)
  })

  const PAGE_SIZE = 6
  const paginated = filtered.slice(0, page * PAGE_SIZE)
  const hasMore = paginated.length < filtered.length

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-normal text-white nx-display">Education Hub</h1>
        <p className="text-sm text-[#A1A1AA] mt-1 font-['JetBrains_Mono',monospace]">
          Learn about sustainability, climate change, and eco-friendly living
        </p>
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#A1A1AA]" aria-hidden="true" />
        <input
          type="search"
          placeholder="Search articles…"
          value={searchQuery}
          onChange={(e) => { setSearchQuery(e.target.value); setPage(1) }}
          aria-label="Search articles"
          className="w-full h-10 pl-10 pr-4 text-sm rounded-lg border border-[#30354A] bg-[#1a1e2a] text-white font-['JetBrains_Mono',monospace] placeholder:text-[#A1A1AA]/50 focus:outline-none focus:ring-2 focus:ring-[#2D8CFF]"
        />
      </div>

      {/* Category filter */}
      <div className="flex gap-2 flex-wrap" role="group" aria-label="Filter by category">
        {CATEGORIES.map(({ id, label }) => (
          <button
            key={label}
            onClick={() => { setCategory(id); setPage(1) }}
            aria-pressed={category === id}
            className={clsx(
              'px-4 py-1.5 rounded-full text-xs font-semibold transition-all duration-200 font-[\'JetBrains_Mono\',monospace]',
              category === id
                ? 'bg-[#2D8CFF] text-white shadow-[0_0_12px_rgba(45,140,255,0.3)]'
                : 'bg-[#262A34] border border-[#30354A] text-[#A1A1AA] hover:bg-[#30354A] hover:text-white'
            )}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Articles grid */}
      {loading ? (
        <div className="flex justify-center h-40 items-center">
          <Loader2 className="w-8 h-8 text-[#2D8CFF] animate-spin" aria-label="Loading articles" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-12 text-[hsl(var(--muted-foreground))]">
          <BookOpen className="w-12 h-12 mx-auto mb-3 opacity-40" aria-hidden="true" />
          <p>No articles found for "{searchQuery}"</p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {paginated.map((article) => (
              <Card key={article.id} hover className="flex flex-col">
                <CardContent className="p-5 flex-1 flex flex-col">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-xl" aria-hidden="true">{getCategoryIcon(article.category)}</span>
                    <Badge variant="eco" className="text-xs capitalize">
                      {article.category?.replace(/_/g, ' ') || 'General'}
                    </Badge>
                  </div>
                  <h3 className="font-semibold mb-2 leading-snug line-clamp-2 text-white font-['JetBrains_Mono',monospace]">{article.title}</h3>
                  <p className="text-xs text-[#A1A1AA] leading-relaxed flex-1 line-clamp-3 font-['JetBrains_Mono',monospace]">
                    {article.summary || article.content?.slice(0, 120) + '…'}
                  </p>
                  <div className="flex items-center justify-between mt-4 pt-4 border-t border-[#30354A]">
                    <div className="flex items-center gap-2 text-xs text-[#A1A1AA] font-['JetBrains_Mono',monospace]">
                      <Clock className="w-3 h-3" aria-hidden="true" />
                      {article.readTime || '5 min read'} · {formatDate(article.publishedAt)}
                    </div>
                    <button
                      onClick={() => setActiveArticle(article)}
                      aria-label={`Read article: ${article.title}`}
                      className="text-[#2D8CFF] hover:text-[#66b3ff] hover:underline text-xs font-medium flex items-center gap-1 font-['JetBrains_Mono',monospace] transition-colors"
                    >
                      Read <ChevronRight className="w-3 h-3" />
                    </button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {hasMore && (
            <div className="text-center">
              <Button variant="outline" onClick={() => setPage((p) => p + 1)} aria-label="Load more articles">
                Load More Articles
              </Button>
            </div>
          )}
        </>
      )}

      {/* Article Modal */}
      {activeArticle && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
          <div className="bg-[#0B0F19] border border-[#30354A] rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col overflow-hidden relative">
            <button
              onClick={() => setActiveArticle(null)}
              className="absolute top-4 right-4 p-2 rounded-full hover:bg-[#262A34] text-[#A1A1AA] hover:text-white transition-colors"
              aria-label="Close article"
            >
              <X className="w-5 h-5" />
            </button>
            
            <div className="p-8 overflow-y-auto">
              <div className="flex items-center gap-2 mb-4">
                <span className="text-2xl" aria-hidden="true">{getCategoryIcon(activeArticle.category)}</span>
                <Badge variant="eco" className="text-sm capitalize">
                  {activeArticle.category?.replace(/_/g, ' ') || 'General'}
                </Badge>
              </div>
              
              <h2 className="text-2xl font-semibold mb-4 text-white font-['JetBrains_Mono',monospace] leading-tight">
                {activeArticle.title}
              </h2>
              
              <div className="flex items-center gap-4 text-sm text-[#A1A1AA] mb-8 font-['JetBrains_Mono',monospace] border-b border-[#30354A] pb-6">
                <div className="flex items-center gap-1.5">
                  <Clock className="w-4 h-4" aria-hidden="true" />
                  {activeArticle.readTime || '5 min read'}
                </div>
                <div>·</div>
                <div>{formatDate(activeArticle.publishedAt)}</div>
              </div>

              <div className="prose prose-invert max-w-none">
                <p className="text-lg text-white/90 leading-relaxed mb-6">
                  {activeArticle.summary}
                </p>
                
                {activeArticle.content ? (
                  <div dangerouslySetInnerHTML={{ __html: activeArticle.content }} />
                ) : (
                  <div className="space-y-4 text-[#A1A1AA] leading-relaxed">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                  </div>
                )}
              </div>
            </div>
            
            <div className="p-4 border-t border-[#30354A] bg-[#0B0F19]/50 flex justify-end">
              <Button onClick={() => setActiveArticle(null)}>
                Close
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
